### ISSUE TITLE
url field containing fullpath

### ISSUE THREAD

**Issue by lbesnard** [aodn/talend-components#33]
## Description of the problem

The retrieved URL of each file contains the full path. This is problematic, because the prefix has to be hardcoded in the portal :
https://github.com/aodn/aodn-portal/blob/master/grails-app/conf/Config.groovy#L155

This appeared also to be a problem in the development of new features for the IMOS user code library. 
see comment : https://github.com/aodn/imos-user-code-library/blob/geoserver_powerusers_matlab/MATLAB_R2011/demos/geoserver/geoserver_example_jason_everett.m#L43

This file is an example for power users who are looking for their original NetCDF files from a specific deployment.

## Solution

Maybe the 'URL component' could get rid of the prefix, and replace it with http://data.aodn.org.au/ ... or something similar.

@danfruehauf any comments about this . @pblain @jonescc

**Comment by danfruehauf** [comment]
Has to be solved. 100% perspiration, 0% inspiration.

I'd even go further and say that the whole filesystem structure should be thought of.

**Comment by jonescc** [comment]
Resolved during migration to manifest harvesting/pipeline processing.
